# Generated by Django 4.0 on 2021-12-27 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('coautor', models.CharField(blank=True, max_length=50)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('emprestado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Livro',
            },
        ),
    ]
