# Generated by Django 4.0 on 2021-12-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='coautor',
        ),
    ]
